var classes = [
    {
        "name": "App\\InfrastructureCalculator\\Calculator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setVirtualMachines",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dispatch",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Infrastructure\\Server",
            "App\\Infrastructure\\VirtualMachine",
            "App\\Infrastructure\\VirtualMachine"
        ],
        "parents": [],
        "lcom": 1,
        "length": 28,
        "vocabulary": 8,
        "volume": 84,
        "difficulty": 6,
        "effort": 504,
        "level": 0.17,
        "bugs": 0.03,
        "time": 28,
        "intelligentContent": 14,
        "number_operators": 8,
        "number_operands": 20,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 18,
        "loc": 52,
        "lloc": 34,
        "mi": 92.1,
        "mIwoC": 52.58,
        "commentWeight": 39.52,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.58,
        "relativeSystemComplexity": 5.58,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 6.33,
        "totalSystemComplexity": 22.33,
        "package": "App\\InfrastructureCalculator\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\Server",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "canFit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dispatch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "freeResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Infrastructure\\AbstractComputer",
            "App\\Infrastructure\\VirtualMachine",
            "App\\Infrastructure\\VirtualMachine"
        ],
        "parents": [
            "App\\Infrastructure\\AbstractComputer"
        ],
        "lcom": 1,
        "length": 22,
        "vocabulary": 6,
        "volume": 56.87,
        "difficulty": 4,
        "effort": 227.48,
        "level": 0.25,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 14.22,
        "number_operators": 6,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 16,
        "loc": 45,
        "lloc": 29,
        "mi": 94.9,
        "mIwoC": 55,
        "commentWeight": 39.89,
        "kanDefect": 0.98,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 25.78,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 77.33,
        "package": "App\\Infrastructure\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\VirtualMachine",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Infrastructure\\AbstractComputer"
        ],
        "parents": [
            "App\\Infrastructure\\AbstractComputer"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Infrastructure\\",
        "pageRank": 0.17,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\Exceptions\\WrongResourceTypeException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Infrastructure\\Exceptions\\",
        "pageRank": 0.08,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\Exceptions\\ServerCannotFitResourceException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Infrastructure\\Exceptions\\",
        "pageRank": 0.08,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\Exceptions\\NullResourceException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Infrastructure\\Exceptions\\",
        "pageRank": 0.08,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\Resource",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsed",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsed",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAvailable",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canFitVm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "allocate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 1,
        "wmc": 10,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Infrastructure\\Exceptions\\WrongResourceTypeException",
            "App\\Infrastructure\\Exceptions\\NullResourceException",
            "App\\Infrastructure\\VirtualMachine",
            "App\\Infrastructure\\Exceptions\\ServerCannotFitResourceException",
            "App\\Infrastructure\\VirtualMachine"
        ],
        "parents": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 22,
        "volume": 298.78,
        "difficulty": 12.86,
        "effort": 3841.48,
        "level": 0.08,
        "bugs": 0.1,
        "time": 213,
        "intelligentContent": 23.24,
        "number_operators": 22,
        "number_operands": 45,
        "number_operators_unique": 8,
        "number_operands_unique": 14,
        "cloc": 30,
        "loc": 81,
        "lloc": 51,
        "mi": 85.34,
        "mIwoC": 44.88,
        "commentWeight": 40.46,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 25.79,
        "totalStructuralComplexity": 175,
        "totalDataComplexity": 5.5,
        "totalSystemComplexity": 180.5,
        "package": "App\\Infrastructure\\",
        "pageRank": 0.25,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Infrastructure\\AbstractComputer",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Infrastructure\\ComputerInterface",
            "App\\Infrastructure\\Resource",
            "App\\Infrastructure\\Resource",
            "App\\Infrastructure\\Resource",
            "App\\Infrastructure\\Resource",
            "App\\Infrastructure\\Resource",
            "App\\Infrastructure\\Resource"
        ],
        "parents": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 9,
        "volume": 79.25,
        "difficulty": 2.57,
        "effort": 203.78,
        "level": 0.39,
        "bugs": 0.03,
        "time": 11,
        "intelligentContent": 30.82,
        "number_operators": 7,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 29,
        "loc": 58,
        "lloc": 29,
        "mi": 99.12,
        "mIwoC": 54.67,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.6,
        "relativeSystemComplexity": 4.6,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 23,
        "totalSystemComplexity": 23,
        "package": "App\\Infrastructure\\",
        "pageRank": 0.23,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    }
]